# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import helloworld_pb2 as protos_dot_helloworld__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/helloworld_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub(object):
    """The greeting service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/helloworld.Greeter/SayHello',
                request_serializer=protos_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=protos_dot_helloworld__pb2.HelloReply.FromString,
                _registered_method=True)
        self.SayHelloStream = channel.unary_stream(
                '/helloworld.Greeter/SayHelloStream',
                request_serializer=protos_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=protos_dot_helloworld__pb2.HelloReply.FromString,
                _registered_method=True)
        self.SayHelloClientStream = channel.stream_unary(
                '/helloworld.Greeter/SayHelloClientStream',
                request_serializer=protos_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=protos_dot_helloworld__pb2.HelloReply.FromString,
                _registered_method=True)
        self.SayHelloBidirectional = channel.stream_stream(
                '/helloworld.Greeter/SayHelloBidirectional',
                request_serializer=protos_dot_helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=protos_dot_helloworld__pb2.HelloReply.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The greeting service definition
    """

    def SayHello(self, request, context):
        """Unary RPC: Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloStream(self, request, context):
        """Server streaming RPC: Returns multiple greetings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloClientStream(self, request_iterator, context):
        """Client streaming RPC: Accepts multiple names
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloBidirectional(self, request_iterator, context):
        """Bidirectional streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=protos_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=protos_dot_helloworld__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHelloStream,
                    request_deserializer=protos_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=protos_dot_helloworld__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SayHelloClientStream,
                    request_deserializer=protos_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=protos_dot_helloworld__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloBidirectional': grpc.stream_stream_rpc_method_handler(
                    servicer.SayHelloBidirectional,
                    request_deserializer=protos_dot_helloworld__pb2.HelloRequest.FromString,
                    response_serializer=protos_dot_helloworld__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helloworld.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/SayHello',
            protos_dot_helloworld__pb2.HelloRequest.SerializeToString,
            protos_dot_helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHelloStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/helloworld.Greeter/SayHelloStream',
            protos_dot_helloworld__pb2.HelloRequest.SerializeToString,
            protos_dot_helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHelloClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/helloworld.Greeter/SayHelloClientStream',
            protos_dot_helloworld__pb2.HelloRequest.SerializeToString,
            protos_dot_helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHelloBidirectional(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/helloworld.Greeter/SayHelloBidirectional',
            protos_dot_helloworld__pb2.HelloRequest.SerializeToString,
            protos_dot_helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
